@startuml
skinparam classAttributeIconSize 0
left to right direction


class RealizaPagamentoUI {
    
}

class RealizaPagamentoController {
    +getListClients()
    +registaPagamento(pag)
}

class ClienteDataHandler {
    +getClienteByEmail()
}

class ProdutoDataHandler {
    +List<Produto> getListaProdutos()
}

class PagamentoDataHandler {
    +validaPagamento(pag)
    +addPagamento(pag)
    +registaPagamento(pag)
}

class EncomendaDataHandler {
    +getEncomendaByCliente()
}

class AplicacaoPOT{
  +static getInstance()
  +getSessaoAtual()
}

class SessaoUtilizador{
  +getEmail()
}


class Encomenda {
  -idEncomenda
  -dataPedida
  -preco
  -pesoEncomenda
  -taxa
  +getPreco()
  +getTaxa()
}

class Pagamento {
  -idPagamento
  -precoTotal
  +create(idEncomenda, precoTotal)
}

class EstadoEncomenda {
  -id_estado_encomenda
  -designacao
}

class Cliente {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -creditos
}

class Produto {
  -idProduto
  -designacao
  -peso
  -precoBase
}

RealizaPagamentoUI .> RealizaPagamentoController
RealizaPagamentoController .> SessaoUtilizador
RealizaPagamentoController .> AplicacaoPOT
RealizaPagamentoController .> ClienteDataHandler
RealizaPagamentoController .> ProdutoDataHandler
RealizaPagamentoController .> EncomendaDataHandler
RealizaPagamentoController .> PagamentoDataHandler

PagamentoDataHandler .> Pagamento
Encomenda "1" -- "1" EstadoEncomenda : tem >
Cliente "1" -- "*" Encomenda: realiza e paga >
Encomenda "1" -- "*" Produto: tem >
Encomenda "1" -- "1" Pagamento: tem >

ClienteDataHandler .> Cliente
EncomendaDataHandler .> Encomenda

@enduml