@startuml
autonumber
actor "Utilizador" as UTIL
participant ":Main" as MAIN
participant ":LerFicheiro" as LF

activate UTIL
UTIL -> MAIN : inicia a aplicação
activate MAIN
loop
MAIN -> LF : read(fileName)
activate LF
deactivate LF
end

MAIN --> UTIL : leitura de dados bem sucedida
deactivate MAIN
deactivate UTIL
@enduml