@startuml
autonumber

actor "Cliente" as CLI
participant ":RealizarEncomendaUI" as UI
participant ":PedirItemFarmaciaController" as CTL
participant ":FarmaciaDB" as FDB

activate CLI
CLI -> UI : pretende realizar a encomenda
activate UI

UI -> CTL : graph = generateGrafo()
activate CTL

CTL -> FDB : generateGrafo()
activate FDB

deactivate FDB
deactivate CTL

UI -> CTL : getFarmaciaProxima(graph, end)
activate CTL

CTL -> FDB : getFarmaciaProxima(graph, enderecoCliente)
activate FDB

deactivate FDB

deactivate CTL

UI --> CLI : operação bem sucedida
deactivate UI

deactivate CLI
@enduml
