@startuml
autonumber
actor "Utilizador" as UTIL

activate UTIL
UTIL -> ":Sistema" : inicia a aplicação
activate ":Sistema"
":Sistema" --> UTIL: leitura de dados bem sucedida
deactivate ":Sistema"
deactivate UTIL

@enduml