@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Cartao {
  -numeroCartao
  -dataDeValidade
  -CCV
}

class Entrega {
  -idEntrega
  -dataInicio
  -dataFim
}

class Encomenda {
  -idEncomenda
  -dataPedida
  -preco
  -pesoEncomenda
  -taxa
}

class EstadoEncomenda {
  -id_estado_encomenda
  -designacao
}

class Produto {
  -idProduto
  -designacao
  -peso
  -precoBase
}

class Estafeta {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -pesoEstafeta
}


class Endereco {
  -morada
  -latitude
  -longitude
  -altitude
}

class Veiculo {
  -idVeiculo
  -descricao
  -tipo
  -percentagemBateria
  -pesoMaximo
  -pesoVeiculo
  -potencia
  -areaFrontal
}

class Parque {
  -idParque
  -numeroMaximo
  -tipo
}

class Cliente {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -creditos
}

class Farmacia {
  -NIF
  -email
  -morada
}

Encomenda "1" -- "1" EstadoEncomenda : tem >
Entrega "1" -- "*" Encomenda : possui >
Estafeta "1" -- "*" Entrega: realiza >
Cliente "1" -- "1" Endereco: tem >
Cliente "1" -- "*" Encomenda: realiza e paga >
Entrega "*" -- "1" Veiculo: realiza <
Encomenda "1" -- "*" Produto: tem >
Parque "1" -- "*" Veiculo: possui >
Cliente "1" -- "1" Cartao: possui >
Farmacia "1" -- "1" Parque: possui >
Farmacia "1" -- "*" Estafeta: tem >
Farmacia "1" -- "1" Endereco: possui >


@enduml