@startuml
autonumber

actor "Administrador" as ADMIN

participant ":AdminUI" as UI
participant ":VeiculoController" as CTRL
participant ":VeiculoDB" as SCHL
participant "veiculo :Veiculo" as SCOOT


activate ADMIN
ADMIN -> UI : inicia a atualização de uma scooter
activate UI
UI -> ADMIN : solicita os dados necessários (percentagem de bateria, peso máximo, pesoVeiculo, potencia, areaFrontal)
ADMIN -> UI : insere os dados 
UI -> CTRL : setVeiculo(percentagem de bateria,peso máximo,pesoVeículo,potencia,areaFrontal)
activate CTRL
CTRL -> SCHL : setVeiculo(percentagem de bateria,peso máximo,pesoVeículo,potencia,areaFrontal)
activate SCHL
SCHL -> SCOOT : veiculo = setVeiculo(percentagem de bateria,peso máximo,pesoVeículo,potencia,areaFrontal)
activate SCOOT 
deactivate SCOOT
deactivate SCHL
deactivate CTRL
  
UI --> ADMIN : apresenta dos dados e solicita confirmação
deactivate UI

ADMIN -> UI : confirma os dados da scooter
activate UI 
UI -> CTRL : updateVeiculo()
activate CTRL
CTRL -> SCHL : updateVeiculo(veiculo)
activate SCHL
SCHL -> SCHL : validaVeiculo(veiculo)
SCHL -> SCHL : addVeiculo(veiculo)
deactivate SCHL
deactivate CTRL
deactivate UI
deactivate ADMIN

@enduml