@startuml
skinparam classAttributeIconSize 0

class VeiculoDB {
  +Veiculo setVeiculo(double percentagem de bateria,double peso máximo)
  +scooterHandler(Scooter scooter)
  +validaVeiculo (Veiculo veiculo)
  +addVeiculo (Veiculo veiculo)
}

class VeiculoController {
    +Veiculo setVeiculo(double percentagemBateria, double preco, double peso máximo, double pesoVeiculo, double potencia, double areaFrontal)
    +scooterHandler()
}

class AdminUI {
}

class Veiculo {
   +Veiculo setVeiculo(double percentagemBateria, double preco, double peso máximo, double pesoVeiculo, double potencia, double areaFrontal)
}

AdminUI ..> VeiculoController 

VeiculoController  ..> VeiculoDB
VeiculoDB ..> Veiculo
@enduml