@startuml
autonumber
actor "Administrador" as ADM

participant ":RegistarFarmaciaUI" as UI
participant ":RegistarFarmaciaController" as CTRL
participant "FarmaciaDB" as DB
participant "ParqueDB" as PDB
participant "EnderecoDB" as EDB
participant "farm:Farmacia" as FARMACIA
participant "parque:Parque" as PQ
participant "end:Endereco" as END

activate ADM
ADM -> UI : inicia a criação de uma nova farmácia
activate UI
UI --> ADM : solicita dados da farmácia (NIF, email, morada), endereço do farmácia \n(morada, latitude, longitude e altitude) e quantidade de parques \ne dados do parque (número máximo, tipo e capacidade máxima \nde carregamento)
deactivate UI

ADM -> UI : introduz os dados solicitados
activate UI

loop
UI -> CTRL : novoParque(NIF, numeroMaximo, tipo, maxCap)
activate CTRL
CTRL -> PDB: parque=novoParque(NIF, numeroMaximo, tipo, maxCap)
activate PDB
PDB --> PQ ** : create(NIF, numeroMaximo, tipo, maxCap)
deactivate PDB
deactivate CTRL
end loop

UI -> CTRL : novaFarmacia(NIF, email, morada)
activate CTRL

CTRL -> DB: farm=novaFarmacia(NIF, email, morada)
activate DB
DB --> FARMACIA ** : create(NIF, email, morada)
deactivate DB
deactivate CTRL

UI -> CTRL : novoEndereco(morada, latitude, longitude, altitude)
activate CTRL
CTRL -> EDB: end=novoEndereco(morada, latitude, logitude, altitude)
activate EDB
EDB --> END ** : create(morada, latitude, logitude, altitude)
deactivate EDB
deactivate CTRL

UI --> ADM : apresenta dados e solicita confirmação
deactivate UI

ADM -> UI : confirma
activate UI

UI -> CTRL: registaEndereco(end)
activate CTRL
CTRL ->EDB: registaEndereco(end)
activate EDB
EDB -> EDB: validaEndereco(end)
EDB -> EDB: addEndereco(end)

deactivate EDB
deactivate CTRL

UI -> CTRL: registaFarmacia(farm)
activate CTRL
CTRL ->DB: registaFarmacia(farm)
activate DB
DB -> DB: validaFarmacia(farm)
DB -> DB: addFarmacia(farm)

deactivate DB
deactivate CTRL


UI -> CTRL: registaParques(lparks)
activate CTRL
CTRL ->PDB: registaParques(lparks)
activate PDB
PDB -> PDB: validaParque(parque)
PDB -> PDB: addParque(parque)

deactivate PDB
deactivate CTRL

UI --> ADM : operação bem sucedida
deactivate UI

deactivate ADM

@enduml
