@startuml
skinparam classAttributeIconSize 0

class DroneDB {
  +List<Drone> getDroneList()
  +boolean removeDrone(int id)
}

class DroneController {
    +List<Drone> getDroneList()
    +boolean removeDrone(int id)
}

class DroneUI {
}


DroneUI ..> DroneController 

DroneController ..> DroneDB
@enduml

