@startuml
skinparam classAttributeIconSize 0
left to right direction


class RealizaEncomendaUI {
    
}

class RealizaEncomendaController {
    +getListClients()
    +produtoEncomenda(produto)
    +registaEncomenda(enc)
    +novoRecibo(nifCliente, lista, dataRecibo)
}

class ClienteDataHandler {
    +Cliente getClienteByEmail()
    +getEnderecoCliente(cliente)
}

class ReciboDataHandler {
    +validateRecibo(rec)
    +addRecibo(rec)
    +create(nifCliente, lista, dataRecibo)
}

class ProdutoDataHandler {
    +List<Produto> getListaStock()
    +List<Produto> getListaProdutos()
    +addNovoProduto(produto)
}

class EncomendaDataHandler {
    +Encomenda novaEncomenda(lista, cliente, idEncomenda, dataPedida, preco, peso)
    +registarEncomenda(encomenda)
    +validaEncomenda(enc)
    +addEncomenda(enc)
    +getData()
}

class AplicacaoPOT{
  +static getInstance()
  +getSessaoAtual()
}

class SessaoUtilizador{
  +getEmail()
}



class Entrega {
  -idEntrega
  -dataInicio
  -dataFim
}

class Recibo {
  -idRecibo
  -dataRecibo
  +create(nifCliente, lista, dataRecibo)
}

class Encomenda {
  -idEncomenda
  -dataPedida
  -preco
  -peso
  -taxa
  +create(lista, cliente, idEncomenda, dataPedida, preco, peso)
}

class Produto {
    -idProduto
    -designacao
    -peso
    -precoBase
    +getPeso()
    +getPreco()
}

class Endereco {
  -morada
  -latitude
  -longitude
  +getMorada()
}

class Cliente {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -credito
}

RealizaEncomendaUI .> RealizaEncomendaController
RealizaEncomendaController .> SessaoUtilizador
RealizaEncomendaController .> AplicacaoPOT
RealizaEncomendaController .> ClienteDataHandler
RealizaEncomendaController .> ProdutoDataHandler
RealizaEncomendaController .> EncomendaDataHandler
RealizaEncomendaController .> ReciboDataHandler

ClienteDataHandler .> Cliente
ProdutoDataHandler .> Produto
EncomendaDataHandler .> Encomenda

Recibo "1" -- "1" Encomenda: referente a >
Recibo "1" -- "1" Cliente: referente a >
Entrega "1" -- "*" Encomenda : possui >
Cliente "1" -- "*" Encomenda: realiza e paga >
Encomenda "1" -- "1..*" Produto: tem >
Cliente "1" -- "1" Endereco: tem >

@enduml