@startuml
skinparam classAttributeIconSize 0

class VeiculoDB {
  +getListaVeiculoEntrega(pesoMaximoEntrega, nifFarmacia)
}

class EntregaDB {
  +generateGraphScooter(listEnderecosScooter, listEnderecos, est, v, pesoEntrega)
  +getPath(graphScooter, listEnderecos, finalShortPathScooter, endereco, 0, v)
}

class RegistarEntregaController {
    +getListaVeiculoEntrega(pesoMaximoEntrega, nifFarmacia)
    +generateGraphScooter(listEnderecosScooter, listEnderecos, est, v, pesoEntrega)
    +getPath(graphScooter, listEnderecos, finalShortPathScooter, endereco, 0, v)
}

class RegistarEntregaUI {
}


class Entrega {
  -Integer idEntrega
  -String dataInicio
  -String dataFim
  -Double pesoEntrega
}

class Estafeta {
  -Double pesoEstafeta
}


class Veiculo {
  -Integer idVeiculo
  -String descricao
  -Double percentagemBateria
  -Double pesoMaximo
  -Double pesoVeiculo
  -Double potencia
  -Double areaFrontal
}


Estafeta "1" -- "*" Entrega: realiza >
Entrega "*" -- "1" Veiculo: realiza <
VeiculoDB "1" -- "*" Veiculo: tem registadas >
EntregaDB "1" -- "*" Entrega: tem registadas >

RegistarEntregaUI ..> RegistarEntregaController 

RegistarEntregaController ..> VeiculoDB
RegistarEntregaController ..> EntregaDB


@enduml