@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Entrega {
  -idEntrega
  -dataInicio
  -dataFim
  -pesoEntrega
}

class Estafeta {
  -pesoEstafeta
}


class Veiculo {
  -idVeiculo
  -descricao
  -percentagemBateria
  -pesoMaximo
  -pesoVeiculo
  -potencia
  -areaFrontal
}

Estafeta "1" -- "*" Entrega: realiza >
Entrega "*" -- "1" Veiculo: realiza <

@enduml