@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction


class Encomenda {
  -idEncomenda
  -dataPedida
  -preco
  -peso
  -taxa
}

class Produto {
  -idProduto
  -designacao
  -peso
  -precoBase
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

class Endereco {
  -morada
  -latitude
  -longitude
}

class Cliente {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -creditos
}


Cliente "1" -- "1" Utilizador: atua como >
Cliente "1" -- "*" Encomenda: realiza e paga >
Encomenda "1" -- "1..*" Produto: tem >
Cliente "1" -- "1" Endereco: tem >

@enduml