@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction


class Encomenda {
  -idEncomenda
  -dataPedida
  -preco
  -peso
  -taxa
}

class Recibo {
  -idRecibo
  -precoTotal
  -lista
  -dataRecibo
}

class Produto {
  -idProduto
  -designacao
  -peso
  -precoBase
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

class Endereco {
  -morada
  -latitude
  -longitude
}

class Cliente {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -creditos
}

class EstadoEncomenda {
  -id_estado_encomenda
  -designacao
}


Encomenda "1" -- "1" EstadoEncomenda : tem >
Cliente "1" -- "1" Utilizador: atua como >
Cliente "1" -- "*" Encomenda: realiza e paga >
Encomenda "1" -- "1..*" Produto: tem >
Cliente "1" -- "1" Endereco: tem >
Recibo "1" -- "1" Encomenda: referente a >
Recibo "1" -- "1" Cliente: referente a >

@enduml