@startuml
autonumber
actor "Cliente" as UNR

activate UNR
UNR -> ":Sistema" : Pretende realizar a encomenda
activate ":Sistema"
":Sistema" --> UNR : apresenta lista de produtos em stock e solicita os produtos para a encomenda
deactivate ":Sistema"


UNR -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> UNR : apresenta dados e solicita confirmação
deactivate ":Sistema"

UNR -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> UNR : gera o recibo e informa que a operação foi bem sucedida
deactivate ":Sistema"

deactivate UNR
@enduml