@startuml
skinparam classAttributeIconSize 0

class Parque {
  -Integer numeroMaximo
  +getNumMax()
}

class Estacionamento {
  -Integer numeroLote
  -Integer carregador
  -Integer NIF
  +Estacionamento(numeroLote, carregador, NIF)
}

class ParqueDB {
  +getNumMaxParqueByNIF(NIF)
}

class EstacionamentoDB {
  +Estacionamento novoEstacionamento(numeroLote, carregador, NIF)
  +registaEstacionamento(estac)
  +validaEstacionamento(estac)
}

class InserirEstacionamentosController {
    +getNumMaxParqueByNIF(NIF)
    +novoEstacionamento(numeroLote, carregador, NIF)
    +registaEstacionamentos(lEstac)
}

class InserirEstacionamentosUI {
}

InserirEstacionamentosUI ..> InserirEstacionamentosController
InserirEstacionamentosController ..> ParqueDB
InserirEstacionamentosController ..> Parque
InserirEstacionamentosController ..> EstacionamentoDB
InserirEstacionamentosController ..> Estacionamento

ParqueDB "1" --> "*" Parque : possui
Parque "1" --> "*" Estacionamento : tem
EstacionamentoDB "1" --> "*" Estacionamento : possui

@enduml
