@startuml
autonumber

actor "Administrador" as ADM
participant ":InserirEstacionamentosUI" as UI
participant ":InserirEstacionamentosController" as CTL
participant ":AplicacaoPOT" as _APP
participant "app:\nAplicacaoPOT" as APP
participant ":ParqueDB" as PDB
participant ":EstacionamentoDB" as EDB
participant "estac:Estacionamento" as ESTAC

activate ADM
ADM -> UI : inserção de estacionamentos
activate UI
UI --> ADM : solicita dados do parque (NIF da farmácia)
deactivate UI

ADM -> UI : introduz os dados solicitados

activate UI
UI -> CTL : numMax = getNumMaxParqueByNIF(NIF)
activate CTL
CTL -> PDB : numMax = getNumMaxParqueByNIF(NIF)
activate PDB
deactivate PDB
deactivate CTL

loop
UI --> ADM : solicita dados dos estacionamentos (disponibilidade do carregador)
deactivate UI

ADM --> UI : introduz os dados solicitados
activate UI

UI -> CTL : novoEstacionamento(numeroLote, carregador, NIF)
activate CTL

CTL -> EDB: estac = novoEstacionamento(numeroLote, carregador, NIF)
activate EDB

EDB --> ESTAC ** : create(numeroLote, carregador, NIF)

deactivate EDB
deactivate CTL
end

UI --> ADM : apresenta dados dos estacionamentos e solicita confirmação
deactivate UI
ADM -> UI : confirma
activate UI
UI -> CTL : registaEstacionamentos(lEstac)

loop
activate CTL
CTL -> EDB :registaEstacionamento(estac)
activate EDB

EDB -> EDB : validaEstacionamento(estac)
deactivate EDB
deactivate CTL
end
UI --> ADM: informa sucesso da operação

deactivate UI
deactivate ADM
@enduml
