@startuml
autonumber
actor "Administrador" as ADM

activate ADM
ADM -> ":Sistema" : Pretende inserir estacionamentos de um parque de uma farmácia
activate ":Sistema"

":Sistema" --> ADM : solicita dados do parque (NIF da farmácia) e dos estacionamentos \n(disponibilidade do carregador)
deactivate ":Sistema"

ADM -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"

":Sistema" --> ADM : apresenta dados e solicita confirmação
deactivate ":Sistema"

ADM -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> ADM : operação bem sucedida
deactivate ":Sistema"

deactivate ADM
@enduml
