@startuml
autonumber
actor "Administrador" as UNR

activate UNR
UNR -> ":Sistema" : Pretende adicionar uma nova drone
":Sistema" --> UNR : solicita dados do drone(descrição, percentagem de bateria, peso do drone e peso máximo)
deactivate ":Sistema"


UNR -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> UNR : apresenta dados e solicita confirmação
deactivate ":Sistema"

UNR -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> UNR : operação bem sucedida
deactivate ":Sistema"

deactivate UNR
@enduml
