@startuml
autonumber

actor "Administrador" as ADMIN

participant ":DroneUI" as UI
participant ":DroneController" as CTRL
participant ":DroneDB" as DRDB
participant "drone :Drone" as DRON
activate ADMIN
ADMIN -> UI : inicia a adição de novo drone
activate UI
UI -> ADMIN : solicita os dados necessários do drone
deactivate UI
ADMIN -> UI : insere os dados (descrição,percentagem de bateria, peso máximo, peso do drone,potencia, área frontal, estado)
activate UI
UI -> CTRL : addDrone(descrição,percentagem de bateria, peso máximo, peso do drone,potencia, área frontal, estado)
activate CTRL
CTRL -> DRDB : addDrone(descrição,percentagem de bateria, peso máximo, peso do drone,potencia, área frontal, estado)
activate DRDB
deactivate DRDB
CTRL -> DRDB : drone = newDrone(descrição,percentagem de bateria, peso máximo, peso do drone,potencia, área frontal, estado)
activate DRDB
DRDB -> DRON : create (descrição,percentagem de bateria, peso máximo, peso do drone,potencia, área frontal, estado)
activate DRON
deactivate DRON
deactivate DRDB
deactivate CTRL
  
UI --> ADMIN : apresenta dos dados e solicita confirmação
deactivate UI

ADMIN -> UI : confirma os dados do drone
activate UI 
UI -> CTRL : droneDB()
activate CTRL
CTRL -> DRDB : droneDB(drone)
activate DRDB
DRDB -> DRDB : validaDrone(drone)
DRDB -> DRDB : addDrone(drone)
deactivate DRDB
deactivate CTRL
deactivate UI
deactivate ADMIN

@enduml

