@startuml
autonumber

actor "Administrador" as ADMIN

participant ":ScooterUI" as UI
participant ":ScooterController" as CTRL
participant ":ScooterDB" as SCHL
participant "scooter :Scooter" as SCOOT

activate ADMIN
ADMIN -> UI : inicia a adição de nova scooter
activate UI
UI -> ADMIN : questiona se pretende que a scooter tenha número único ou QrCode
deactivate UI

alt 
ADMIN -> UI : escolhe id
activate UI
UI -> CTRL : generateIdScooter()
activate CTRL
CTRL -> SCHL : idScooter = generateIdScooter()
activate SCHL
deactivate SCHL 
deactivate CTRL
end alt

alt 
ADMIN -> UI : escolhe QrCode
UI -> CTRL : generateQrCode()
activate CTRL
CTRL -> SCHL : qrCode = generateQrCode()
activate SCHL
deactivate SCHL
deactivate CTRL
end alt

UI -> ADMIN : solicita os restantes dados necessários da scooter
deactivate UI
ADMIN -> UI : insere os dados (percentagem de bateria, peso da scooter e peso máximo)
activate UI
UI -> CTRL : addNewScooter(percentagem de bateria,peso da scooter,peso máximo)
activate CTRL
CTRL -> SCHL : addNewScooter(percentagem de bateria,peso da scooter, peso máximo)
activate SCHL
deactivate SCHL
CTRL -> SCHL : scooter = new Scooter(idScooter,percentagem de bateria,peso da scooter, peso máximo)
activate SCHL
SCHL -> SCOOT : create (idScooter,percentagem de bateria, peso da scooter, peso máximo)
activate SCOOT
deactivate SCOOT
deactivate SCHL
deactivate CTRL
  
UI --> ADMIN : apresenta dos dados e solicita confirmação
deactivate UI

ADMIN -> UI : confirma os dados da scooter
activate UI 
UI -> CTRL : scooterHandler()
activate CTRL
CTRL -> SCHL : scooterHandler(scooter)
activate SCHL
SCHL -> SCHL : validaScooter(scooter)
SCHL -> SCHL : addScooter(scooter)
deactivate SCHL
deactivate CTRL
deactivate UI
deactivate ADMIN

@enduml
