@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Farmacia {
  -NIF
  -email
}

class Estafeta {
  -pesoEstafeta
}

class EstadoEstafeta {
  -id
  -designacao
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

Estafeta "1" -- "1" EstadoEstafeta: tem >
Estafeta "1" -- "1" Utilizador: atua como >
Administrador "1" -- "1" Utilizador: atua como >
Administrador "1" -- "*" Estafeta: regista >
Farmacia "1" -- "*" Estafeta: tem >
Farmacia "1" -- "1" Administrador: tem >

@enduml