@startuml
autonumber
actor "Estafeta" as EST

activate EST
EST -> ":Sistema" : inicia entrega 
activate ":Sistema"
":Sistema" --> EST : solicita o id de uma entrega
deactivate ":Sistema"

EST -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> EST : apresenta a energia minima percorrida durante a entrega
deactivate ":Sistema"

deactivate EST
@enduml