@startuml
autonumber
actor "Estafeta" as EST

activate EST
EST -> ":Sistema" : inicia entrega 
activate ":Sistema"
":Sistema" --> EST : mostra a lista de entregas do estafeta e solicita escolha de uma entrega
deactivate ":Sistema"

EST -> ":Sistema" : introduz dados solicitados
activate ":Sistema"
":Sistema" --> EST : apresenta dados e solicita confirmação
deactivate ":Sistema"

EST -> ":Sistema" : confirma os dados
activate ":Sistema"
":Sistema" --> EST : informa operação bem sucedida
deactivate ":Sistema"

deactivate EST
@enduml