@startuml
skinparam classAttributeIconSize 0

class EmailDB {
  +sendEmali(emailOrig,emailDest,assunto,mensagem)
}

class EnviarNotaTransferenciaController {
    +enviarNotaTransferencia(fOrig,fDest,prod,qntd)
}

class EnviarNotaTransferenciaUI {
}

EnviarNotaTransferenciaUI ..> EnviarNotaTransferenciaController
EnviarNotaTransferenciaController ..> EmailDB

@enduml
