@startuml
autonumber

actor "Plataforma" as MAIN
participant ":EstacionamentoController" as NCONT

MAIN -> NCONT: checkParkings(String path)
activate MAIN
activate NCONT

NCONT -> NCONT: checkDirectory(String path)
NCONT -> NCONT: simulateParkingVeiculo(String path)
NCONT -> "VeiculoDB": veiculo = getVeiculoById(VeiculoId)
activate "VeiculoDB"
deactivate "VeiculoDB"
NCONT -> "EstacionamentoDB": estacionamento = getEstacionamentoById(numeroLote)
activate "EstacionamentoDB"
deactivate "EstacionamentoDB"
NCONT -> "ParqueDB": parque = getParqueByID(idParque)
activate "ParqueDB"
deactivate "ParqueDB"
NCONT -> "EstafetaDB": estafeta = getUtilizadorEstafetaByNIF(nifEstafeta)
activate "EstafetaDB"
deactivate "EstafetaDB"

alt estimativa = -1
    NCONT -> NCONT: notificaEstafeta(false,estimativa,emailEstafeta)
    note right: "estimativa = -1" ocorre quando a simulação de\nestacionamento é mal efetuada
    NCONT -> "EmailDB": sendEmail(emailOrig, email, assunto, mensagem);
else
    ref over NCONT
    SimulaçãoBemEfetuada
    end ref
end
deactivate MAIN
deactivate NCONT
@enduml