@startuml
autonumber

actor "Administrador" as ADMIN

participant ":ScooterUI" as UI
participant ":ScooterController" as CTRL
participant ":ScooterDB" as SCHL
participant "scooter :Scooter" as SCOOT


activate ADMIN
ADMIN -> UI : inicia a remoção de scooter
activate UI
UI -> CTRL : getScooterList()
activate CTRL

CTRL -> SCHL : getScooterList()
activate SCHL
deactivate SCHL
deactivate CTRL
  
UI --> ADMIN : apresenta a lista de scooters e solicita o id da scooter a remover
deactivate UI

ADMIN -> UI : insere o id da scooter
activate UI 
UI -> CTRL : removeScooter(id)
activate CTRL
CTRL -> SCHL : removeScooter(id)
activate SCHL
deactivate SCHL
deactivate CTRL
UI --> ADMIN : solicita confirmação
deactivate UI

ADMIN -> UI : confirma
activate UI
UI --> ADMIN : informa o administrador do sucesso da operação
deactivate UI
deactivate ADMIN

@enduml