@startuml
autonumber

actor "Administrador" as ADMIN

participant ":AdminUI" as UI
participant ":RegistarEntregaController" as CTRL
participant ":EncomendaDB" as DRDB
participant ":EntregaDB" as ENDB



activate ADMIN
ADMIN -> UI : pretende saber qual a entrega mais eficiente
activate UI
UI -> CTRL : getListaEncomenda()
activate CTRL
CTRL -> DRDB : listaEncomenda = getListaEncomenda()
activate DRDB
deactivate DRDB
deactivate CTRL
  
UI --> ADMIN : solicita uma lista de encomendas
deactivate UI

ADMIN -> UI : introduz os dados solicitados
activate UI 
UI -> CTRL : getEntregaEficiente(listaEncomendas)
activate CTRL
CTRL -> ENDB : getEntregaEficiente(listaEncomendas)
activate ENDB
deactivate ENDB
deactivate CTRL
UI --> ADMIN : apresenta os dados
deactivate UI

deactivate ADMIN

@enduml
