@startuml
autonumber

actor "Estafeta" as ADMIN

participant ":RegistarEntregUI" as UI
participant ":RegistarEntregaController" as CTRL
participant ":VeiculoDB" as DRDB
participant ":EntregaDB" as ENDB



activate ADMIN
ADMIN -> UI : pretende saber qual a entrega mais eficiente
activate UI
UI -> CTRL : getListaVeiculoEntrega(pesoMaximoEntrega)
activate CTRL
CTRL -> DRDB : listaVeiculos = getListaVeiculoEntrega(pesoMaximoEntrega)
activate DRDB
deactivate DRDB
deactivate CTRL
loop
UI -> CTRL : generateGraphScooter(listEnderecosScooter, listEnderecos, est, v, pesoEntrega)
activate CTRL
CTRL -> ENDB : generateGraphScooter(listEnderecosScooter, listEnderecos, est, v, pesoEntrega)
activate ENDB
deactivate ENDB
deactivate CTRL
UI -> CTRL : getPath(graphScooter, listEnderecos, finalShortPathScooter, endereco, 0, v)
activate CTRL
CTRL -> ENDB : getPath(graphScooter, listEnderecos, finalShortPathScooter, endereco, 0, v)
activate ENDB
deactivate ENDB
deactivate CTRL
end loop
UI --> ADMIN : apresenta os dados
deactivate UI

deactivate ADMIN

@enduml
