@startuml
autonumber
actor "Estafeta" as UNR

activate UNR
UNR -> ":Sistema" : Pretende saber qual a entrega mais eficiente
activate ":Sistema"

":Sistema" --> UNR : apresenta os dados
deactivate ":Sistema"

deactivate UNR
@enduml
