@startuml
skinparam classAttributeIconSize 0

class SessaoUtilizador{
  +static getInstance()
  +getSessaoAtual()
  +getNif()
}

class Entrega {
  -Integer idEntrega
  -String dataInicio
  -String dataFim
  -Double pesoEntrega
  +create(dataInicio, dataFim, veiculo, nif, pesoMaximo)
}

class EntregaDB {
  +addEntrega(dataInicio, dataFim, veiculo, nif, pesoMaximo)
  +registaEntrega(entr)
  +validaEntrega(entr)
  +addEntrega(entr)
}

class EstafetaDB {
  +getEstafetaByNIF(nif)
}

class RegistarEntregaController {
  +getEstafeta()
  +addEntrega(dataInicio, dataFim, veiculo, nif, pesoMaximo)
  +registaEntrega()
}

class RegistarEntregaUI {
}

class Encomenda {
  -Integer idEncomenda
  -String dataPedida
  -Double preco
  -Double pesoEncomenda
  -Double taxa
}

class Estafeta {
  -Double pesoEstafeta
}

class Veiculo {
  -Integer idveiculo
  -String descricao
  -Double capacidade
  -Double percentagemBateria
  -Double pesoMaximo
  -Double pesoVeiculo
  -Double potencia
  -Double areaFrontal
}

class Drone {
  -Integer idDrone
  -Double largura
}

class Scooter {
  -Integer idScooter
}

class EstadoEncomenda {
  -Integer idEstadoEncomenda
  -String designacao
}

class Utilizador{
  -String NIF
  -String nome
  -String email
  -Integer numeroSegurancaSocial
  -String password
  }

RegistarEntregaUI ..> RegistarEntregaController

RegistarEntregaController ..> EstafetaDB
RegistarEntregaController ..> EntregaDB
RegistarEntregaController ..> AplicacaoPOT
RegistarEntregaController ..> SessaoUtilizador

EntregaDB "1" --> "*" Entrega : tem registadas
EstafetaDB "1" --> "*" Estafeta : tem registadas
Encomenda "1" -- "1" EstadoEncomenda : tem >
Entrega "1" -- "*" Encomenda : possui >
Estafeta "1" -- "*" Entrega: realiza >
Entrega "*" -- "1" Veiculo: realiza <
Estafeta "1" -- "1" Utilizador: atua como >
Veiculo "1" -- "1" Drone: é <
Veiculo "1" -- "1" Scooter: é <

@enduml