@startuml
autonumber
actor "Estafeta" as EST

participant ":RegistarEntregaUI" as UI
participant ":RegistarEntregaController" as CTRL
participant "sessao\n:SessaoUtilizador" as SESSAO
participant ":EstafetaDB" as ESTDB
participant ":EntregaDB" as ENTRDB
participant "entr:Entrega" as ENTR

activate EST
EST -> UI : inicia registo de entrega
activate UI
UI -> CTRL : getEstafeta()
activate CTRL
CTRL -> SESSAO: app = getInstance()
activate SESSAO
|||
deactivate SESSAO
CTRL -> SESSAO: sessao = getSessaoAtual()
activate SESSAO
|||
deactivate SESSAO

CTRL -> SESSAO: nif = getNif()
activate SESSAO
|||
deactivate SESSAO
CTRL -> ESTDB : est = getEstafetaByNIF(nif)
activate ESTDB
deactivate ESTDB
deactivate CTRL
UI --> EST : solicita o nif da farmacia e o peso maximo da entrega
deactivate UI

EST -> UI : introduz dados solicitados
activate UI
UI -> CTRL: addEntrega(dataInicio, dataFim, veiculo, nif, pesoMaximo)
activate CTRL
CTRL -> ENTRDB : entr = addEntrega(dataInicio, dataFim, veiculo, nif, pesoMaximo)
activate ENTRDB
ENTRDB -> ENTR ** : create(dataInicio, dataFim, veiculo, nif, pesoMaximo)

deactivate ENTRDB
deactivate CTRL
UI --> EST : apresenta dados e solicita confirmação
deactivate UI

EST -> UI : confirma os dados
activate UI
UI -> CTRL : registaEntrega()
activate CTRL
CTRL-> ENTRDB : registaEntrega(entr)
activate ENTRDB
ENTRDB -> ENTRDB : validaEntrega(entr)
ENTRDB -> ENTRDB : addEntrega(entr)
deactivate ENTRDB

UI --> EST : informa operação bem sucedida
deactivate CTRL
deactivate UI

deactivate EST

@enduml