@startuml
skinparam classAttributeIconSize 0

class EmailDB {
  +sendEmali(emailOrig,emailDest)
}

class PedirItemFarmaciaController {
    +enviarNotaEntrega(fOrig,fDest)
}

class RealizaEncomendaUI {
}

RealizaEncomendaUI ..> PedirItemFarmaciaController
PedirItemFarmaciaController ..> EmailDB

@enduml