@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Entrega {
  -idEntrega
  -dataInicio
  -dataFim
}


class Estacionamento {
  -numeroLote
  -carregador
}

class Estafeta {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

class EstadoEstafeta {
  -id_estado_estafeta
  -designacao
}


class Scooter {
  -idScooter
  -percentagemBateria
  -pesoMaximo
}

class Parque {
  -numeroMaximo
}


Estafeta "1" -- "*" Entrega: realiza >
Estafeta "1" -- "1" EstadoEstafeta: tem >
Entrega "*" -- "1" Scooter: realiza <
Parque "1" -- "*" Scooter: possui >
Parque "1" -- "*" Estacionamento: tem >
Estacionamento "1" -- "1" Scooter: tem >

@enduml