@startuml
autonumber

actor "Estafeta" as EST
participant ":NotificarEstafetaUI" as NUI
participant ":NotificarEstafetaController" as NCONT

activate EST
EST -> NUI: informa sobre estacionamento da scooter
activate NUI
NUI -> NCONT: checkWellDockedScooter()
activate NCONT


NCONT -> "AplicacaoPOT": app = getInstance()
activate "AplicacaoPOT"
deactivate "AplicacaoPOT"

NCONT -> "app:AplicacaoPOT": sessao = getSessaoAtual()
activate "app:AplicacaoPOT"
deactivate "app:AplicacaoPOT"

NCONT ->  "sessao: SessaoUtilizador": email = getEmail()
activate "sessao: SessaoUtilizador"
deactivate "sessao: SessaoUtilizador"

NCONT -> "EstafetaDB": est = getEstafetaByEmail(email)
activate "EstafetaDB"
deactivate "EstafetaDB"

NCONT -> "EntregaDB": ent = getActiveEntrega(est)
activate "EntregaDB"
deactivate "EntregaDB"

NCONT -> "ent: Entrega": scoot = getScooter()
activate "ent: Entrega"
deactivate "ent: Entrega"

NCONT -> "EstacionamentoScooterDB": estac = getActiveParking(scoot)
activate "EstacionamentoScooterDB"
deactivate "EstacionamentoScooterDB"

NCONT -> NCONT: estimativa = calcEstimativa(scoot,estac)

deactivate NCONT

NUI -> EST: notifica que a scooter foi bem estacionada e mostra a estimativa



deactivate EST
deactivate NUI

@enduml