@startuml
autonumber

participant ":EstacionamentoController" as NCONT
participant "EmailDB" as EDB
participant "timer\n:Timer" as TIMER
participant "timerTask:\nTimerTask" as TTASK

activate NCONT
-> NCONT: notificaEstafeta(true, estimativa, email)

NCONT-> NCONT: timerCarregamento(estimativa, veiculo)
NCONT -> EDB: sendEmail(emailOrig, email, assunto, mensagem)
activate EDB
deactivate EDB
NCONT -> TIMER **: new Timer()
NCONT -> TTASK **: new TimerTask()

ref over NCONT,TIMER
schedule(timerTask,carregamentoCompleto(veiculo))
end ref

deactivate NCONT
@enduml