@startuml
autonumber
actor "Cliente" as UNR

activate UNR
UNR -> ":Sistema" : Acaba de fazer a encomenda

activate ":Sistema"
":Sistema" --> UNR : Gera o recibo e finaliza a tarefa
deactivate ":Sistema"

deactivate UNR
@enduml