@startuml
skinparam classAttributeIconSize 0

class TransferenciaProduto {
  -Integer idTransferencia
  -Integer quantidade
}

class TransferenciaDB {
  +addTransferencia(fOrig,fDest,prod,qtd)
  +enviaStock(fOrig,fDest,prod,qtd)
}

class Farmacia {
  -Integer nif
  -String email
  -String morada
  +Farmacia(nif,email,morada)
}

class FarmaciaDB {
  +getLstFarmaciasByProdutos(p,quant)
  +generateGrafo(farms)
  +getFarmaciaProxima(grafo,nif)
}

class PedirItemFarmaciaController {
    +getListaFarmaciaByProduto(prod,qntd)
    +realizaPedido(fOrig,fDest,prod,qtd)
}

class RealizaEncomendaUI {
}

RealizaEncomendaUI ..> PedirItemFarmaciaController
PedirItemFarmaciaController ..> TransferenciaDB
PedirItemFarmaciaController ..> TransferenciaProduto
PedirItemFarmaciaController ..> FarmaciaDB
PedirItemFarmaciaController ..> Farmacia

FarmaciaDB "1" --> "*" Farmacia : tem registados
TransferenciaDB "1" --> "*" TransferenciaProduto : tem registadas

@enduml
