@startuml
autonumber

actor "Administrador" as ADM
participant ":RealizaEncomendaUI" as UI
participant ":PedirItemFarmaciaController" as CTL
participant ":FarmaciaDB" as FDB
participant ":TransferenciaDB" as TDB

activate ADM
ADM -> UI : novo pedido de produto
activate UI
UI -> CTL : getListaFarmaciaByProduto(prod, qntd)
activate CTL

CTL -> FDB: farms = getLstFarmaciasByProdutos(p, quant)
activate FDB

deactivate FDB

CTL -> FDB : grafo = generateGrafo(farms)
activate FDB
deactivate FDB

CTL -> FDB : fDest = getFarmaciaProxima(grafo,nif)
activate FDB
deactivate FDB

deactivate CTL

UI --> ADM : apresenta farmácia mais próxima com o produto e solitica confirmação
deactivate UI
ADM -> UI : confirma
activate UI
UI -> CTL : realizaPedido(fOrig,fDest,prod,qtd)

activate CTL
CTL -> TDB :realizaPedido(fOrig,fDest,prod,qtd)

activate TDB
TDB -> TDB : addTransferencia(fOrig,fDest,prod,qtd)

TDB -> TDB : enviaStock(fOrig,fDest,prod,qtd)
deactivate TDB
deactivate CTL
UI --> ADM: informa sucesso da operação

deactivate UI
deactivate ADM
@enduml
