@startuml
skinparam classAttributeIconSize 0

class AplicacaoPOT
{
  +static getInstance()
  +getSessaoAtual()
}

class Produto {
  -Integer id
  -String desig
  -Double peso
  -Double preco_base
  +Produto(desig,peso,preco_base)
}

class ProdutosDB {
  +Produto novoProduto(desig,peso,preco_base)
  +getListaProdutos()
  +validaProduto(prod)
  +registaProduto(prod)
  +addProduto(prod)
}

class InserirItensStockController {
    +novoProduto(desig,peso,preco_base)
    +registaProduto(prod)
    +getListaProdutos()
}

class InserirItensStockUI {
}

InserirItensStockUI ..> InserirItensStockController
InserirItensStockController ..> ProdutosDB
InserirItensStockController ..> Produto
InserirItensStockController ..> AplicacaoPOT

ProdutosDB "1" --> "*" Produto : tem registadas

@enduml
