@startuml
autonumber

actor "Administrador" as ADM
participant ":InserirItensStockUI" as UI
participant ":InserirItensStockController" as CTL
participant ":AplicacaoPOT" as _APP
participant "app:\nAplicacaoPOT" as APP
participant ":ProdutosDB" as PDB
participant "prod:Produto" as PROD

activate ADM
ADM -> UI : nova inserção de produto
activate UI
UI -> CTL : getListaProdutos()
activate CTL
CTL -> _APP : app = getInstance()
activate _APP
deactivate _APP
CTL -> APP : sessao = getSessaoAtual()
activate APP
deactivate APP

CTL -> PDB : lp = getListaProdutos()
activate PDB
deactivate PDB

deactivate CTL

UI -> CTL : novoProduto(desig,peso,preco_base)
activate CTL

CTL -> PDB: prod = novoProduto(desig,peso,preco_base)
activate PDB

PDB --> PROD ** : create(desig,peso,preco_base)

deactivate PDB

CTL -> PDB : validaProduto(prod)
activate PDB
deactivate PDB

deactivate CTL

UI --> ADM : apresenta dados dos item e solicita confirmação
deactivate UI
ADM -> UI : confirma
activate UI
UI -> CTL : registaProduto(prod)

activate CTL
CTL -> PDB :registaProduto(prod)

activate PDB
PDB -> PDB : validaProduto(prod)

PDB -> PDB : addProduto(prod)
deactivate PDB
deactivate CTL
UI --> ADM: informa sucesso da operação

deactivate ADM
@enduml
