@startuml
autonumber
actor "Administrador" as ADM

activate ADM
ADM -> ":Sistema" : nova atualização de item do stock
activate ":Sistema"
":Sistema" --> ADM : solicita os dados do processo de atualização \n(i.e. o(s) item(s) a atualizar).
deactivate ":Sistema"

ADM -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> ADM : apresenta os dados, pedindo que os confirme
deactivate ":Sistema"

ADM -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> ADM : operação bem sucedida
deactivate ":Sistema"

deactivate ADM
@enduml
