@startuml
autonumber
actor "Administrador" as ADM

participant ":RegistarFarmaciaUI" as UI
participant ":RegistarFarmaciaController" as CTRL
participant "FarmaciaDB" as DB
participant "ParqueDB" as PDB
participant "EnderecoDB" as EDB
participant "farm:Farmacia" as FARMACIA
participant "parque:Parque" as PQ
participant "end:Endereco" as END

activate ADM
ADM -> UI : inicia a criação de uma nova farmácia
activate UI
UI --> ADM : solicita dados da farmácia (NIF), dados do parque (número máximo e tipo) \ne endereço do parque (morada, latitude, longitude e altitude)
deactivate UI

ADM -> UI : introduz os dados solicitados
activate UI
UI -> CTRL : novaFarmacia(NIF)
activate CTRL

CTRL -> DB: farm=novaFarmacia(NIF)
activate DB
DB --> FARMACIA ** : create(NIF)
deactivate DB
deactivate CTRL

UI -> CTRL : novoEndereco(morada, latitude, longitude, altitude)
activate CTRL
CTRL -> EDB: end=novoEndereco(morada, latitude, logitude, altitude)
activate EDB
EDB --> END ** : create(morada, latitude, logitude, altitude)
deactivate EDB
deactivate CTRL

UI -> CTRL : novoParque(NIF, morada, numeroMaximo, tipo)
activate CTRL
CTRL -> PDB: parque=novoParque(NIF, morada, numeroMaximo, tipo)
activate PDB
PDB --> PQ ** : create(NIF, morada, numeroMaximo, tipo)
deactivate PDB

deactivate CTRL
UI --> ADM : apresenta dados e solicita confirmação
deactivate UI

ADM -> UI : confirma
activate UI

UI -> CTRL: registaFarmacia(farm)
activate CTRL
CTRL ->DB: registaFarmacia(farm)
activate DB
DB -> DB: validaFarmacia(farm)
DB -> DB: addFarmacia(farm)

deactivate DB
deactivate CTRL

UI -> CTRL: registaEndereco(end)
activate CTRL
CTRL ->EDB: registaEndereco(end)
activate EDB
EDB -> EDB: validaEndereco(end)
EDB -> EDB: addEndereco(end)

deactivate EDB
deactivate CTRL

UI -> CTRL: registaParque(parque)
activate CTRL
CTRL ->PDB: registaParque(parque)
activate PDB
PDB -> PDB: validaParque(parque)
PDB -> PDB: addParque(parque)

deactivate PDB
deactivate CTRL

UI --> ADM : operação bem sucedida
deactivate UI

deactivate ADM

@enduml
