@startuml
autonumber
actor "Administrador" as ADM

activate ADM
ADM -> ":Sistema" : inicia a criação de uma nova farmácia
activate ":Sistema"
":Sistema" --> ADM : solicita dados da farmácia (NIF), dados do parque (número máximo e tipo) \ne endereço do parque (morada, latitude, longitude e altitude)
deactivate ":Sistema"

ADM -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> ADM : apresenta dados e solicita confirmação
deactivate ":Sistema"

ADM -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> ADM : operação bem sucedida
deactivate ":Sistema"

deactivate ADM
@enduml