@startuml
skinparam classAttributeIconSize 0

class Cliente {
  -Integer NIF
  -String nome
  -String email
  -String numSegSocial
  -String password
  -Integer numCC
  -String dataValidade
  -Integer CCV
  +Cliente(Integer NIF, String nome, String email, Endereco end, String numSegSocial,\n String password, Integer numCC, String dataValidade, Integer CCV)
}

class Endereco {
  -String morada
  -Double latitude
  -Double longitude
  -Double altitude 
  +Endereco(String morada, Double latitude, Double longitude, Double altitude)
}

class ClienteDB {
  +Cliente novoCliente(Integer NIF, String nome, String email, Endereco end, String numSegSocial,\n String password, Integer numCC, String dataValidade, Integer CCV)
  +validaCliente(Cliente cliente)
  +registaCliente(Cliente cliente)
  -addCliente(Cliente cliente)
}

class EnderecoDB {
  +Endereco novoEndereco(String morada, Double latitude, Double longitude, Double altitude)
  +validaEndereco(Endereco end)
  +registaEndereco(Endereco end)
  -addEndereco(Endereco end)
}

class DefinirClienteController {
  +novoCliente(Integer NIF, String nome, String email, String morada, Double latitude, Double longitude, Double altitude \n String numSegSocial, String password, Integer numCC, String dataValidade, Integer CCV)
  +registaCliente()
}

class DefinirClienteUI {
  
}

DefinirClienteUI ..> DefinirClienteController
DefinirClienteController ..> ClienteDB
DefinirClienteController ..> EnderecoDB
DefinirClienteController ..> Cliente
DefinirClienteController ..> Endereco

ClienteDB "1" --> "*" Cliente : possui
EnderecoDB "1" --> "*" Endereco : possui
Cliente "1" --> "1" Endereco : tem


@enduml
