@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

class Endereco {
  -morada
  -latitude
  -longitude
  -altitude
}

class Cliente {
  -numeroCartaoCredito
  -dataDeValidade
  -CCV
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

Cliente "1" -- "1" Endereco: tem >
Cliente "1" -- "1" Utilizador: atua como >

@enduml