@startuml
autonumber
actor "Cliente" as CL

activate CL
CL -> ":Sistema" : Pretende registar-se
activate ":Sistema"
":Sistema" --> CL : solicita dados do cliente (NIF, nome, email, endereço residencial, localização GPS (latitude, longitude), \nnúmero de segurança social, password, número de cartão de crédito, data de validade, CCV)
deactivate ":Sistema"

CL -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> CL : apresenta dados e solicita confirmação
deactivate ":Sistema"

CL -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> CL : operação bem sucedida
deactivate ":Sistema"

deactivate CL
@enduml