@startuml
autonumber
actor "Administrador" as UNR

activate UNR
UNR -> ":Sistema" : Pretende adicionar um nova drone
":Sistema" --> UNR : solicita dados do drone(descrição, percentagem de bateria, peso do drone, peso máximo, potencia, área frontal,hoverPower)
deactivate ":Sistema"


UNR -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> UNR : apresenta dados e solicita confirmação
deactivate ":Sistema"

UNR -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> UNR : operação bem sucedida
deactivate ":Sistema"

deactivate UNR
@enduml
