@startuml
skinparam classAttributeIconSize 0

class Cliente {
  -Integer NIF
  -String nome
  -String email
  -String numSegSocial
  -String password
  -Integer creditos
  -String morada
  -Integer numCC
  +Cliente(Integer NIF, String nome, String email, String numSegSocial, Integer creditos, String morada, Integer numCC, String password)
}

class Utilizador {
  -Integer NIF
  -String nome
  -String email
  -String numSegSocial
  -String password
  +Utilizador(Integer NIF, String nome, String email, String numSegSocial, String password)
}

class Endereco {
  -String morada
  -Double latitude
  -Double longitude
  -Double altitude 
  +Endereco(String morada, Double latitude, Double longitude, Double altitude)
}

class Cartao {
  -Integer numCC
  -String dataValidade
  -Integer CCV
  +Cartao(Integer numCC, String dataValidade, Integer CCV))
}

class ClienteDB {
  +Cliente novoCliente(Integer NIF, String nome, String email, String numSegSocial, String morada, Integer numCC, String password))
  +validaCliente(Cliente cliente)
  +registaCliente(Cliente cliente)
  -addCliente(Cliente cliente)
}

class UtilizadorDB {
  +registaUtilizador(Cliente cliente)
  +validaUtilizador(Cliente cliente)
  -addUtilizador(Cliente cliente)
}

class EnderecoDB {
  +Endereco novoEndereco(String morada, Double latitude, Double longitude, Double altitude)
  +validaEndereco(Endereco end)
  +registaEndereco(Endereco end)
  -addEndereco(Endereco end)
}

class CartaoDB {
  +Cartao novoCartao(Integer numCC, String dataValidade, Integer CCV)
  +validaCartao(Cartao cc)
  +registaCartao(Cartao cc)
  -addCartao(Cartao cc)
}

class DefinirClienteController {
  +novoCliente(Integer NIF, String nome, String email, String numSegSocial, String morada, Integer numCC, String password)
  +novoEndereco(String morada, Double latitude, Double longitude, Double altitude)
  +novoCartao(Integer numCC, String dataValidade, Integer CCV)
  +registaCliente(Cliente cliente)
  +registaEndereco(Endereco end)
  +registaCartao(Cartao cc)
}

class DefinirClienteUI {
  
}

DefinirClienteUI ..> DefinirClienteController
DefinirClienteController ..> ClienteDB
DefinirClienteController ..> UtilizadorDB
DefinirClienteController ..> EnderecoDB
DefinirClienteController ..> CartaoDB
DefinirClienteController ..> Cliente
DefinirClienteController ..> Utilizador
DefinirClienteController ..> Endereco
DefinirClienteController ..> Cartao

ClienteDB "1" --> "*" Cliente : possui
UtilizadorDB "1" --> "*" Utilizador : possui
EnderecoDB "1" --> "*" Endereco : possui
CartaoDB "1" --> "*" Cartao : possui
Cliente "1" --> "1" Endereco : tem
Cliente "1" --> "1" Cartao : tem
Cliente "1" --> "1" Utilizador : atua como


@enduml
