@startuml
autonumber
actor "Cliente" as CL

activate CL
CL -> ":Sistema" : inicia o seu registo
activate ":Sistema"
":Sistema" --> CL : solicita dados do cliente (NIF, nome, email, creditos, morada, \nnumero de cartao de credito e password), localização GPS (latitude, \nlongitude, altitude), data de validade do CC e CCV
deactivate ":Sistema"

CL -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> CL : apresenta dados e solicita confirmação
deactivate ":Sistema"

CL -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> CL : operação bem sucedida
deactivate ":Sistema"

deactivate CL
@enduml