@startuml
autonumber

actor "Farmácia" as FARM
participant ":EnviarNotaTransferenciaUI" as UI
participant ":EnviarNotaTransferenciaController" as CTL
participant ":ProdutosDB" as PDB
participant ":FarmaciaDB" as FDB

activate FARM
FARM -> UI : envia uma nota de transferência\n com os produtos enviados
activate UI
UI -> CTL : enviarNotaTrans(prods,nif)
activate CTL

CTL -> PDB : lp = getListaProdutos()
activate PDB
deactivate PDB

CTL -> FDB : farm = getFarmacia(nif)
activate FDB
deactivate FDB

CTL -> FDB : enviarNotaTrans(prods,nif)
activate FDB

FDB -> FDB : validaInfo(prods,nif)

FDB -> FDB : enviarNotaTrans(prods,nif)

deactivate FDB

deactivate CTL

UI --> FARM : operação bem sucedida
deactivate UI

deactivate FARM
@enduml
