@startuml
autonumber

actor "Farmácia" as FARM
participant ":RealizarEncomendaUI" as UI
participant ":EnviarNotaTransferenciaController" as CTL
participant ":EmailDB" as EDB

activate FARM
FARM -> UI : envia uma nota de transferência\n com os produtos enviados
activate UI
UI -> CTL : enviarNotaTransferencia(fOrig,fDest,prod,qntd)
activate CTL

CTL -> EDB : sendEmail(emailOrig,emailDest,assunto,mensagem)
activate EDB

deactivate EDB

deactivate CTL

UI --> FARM : operação bem sucedida
deactivate UI

deactivate FARM
@enduml
