@startuml
autonumber

actor "Farmácia" as FARM

activate FARM
FARM -> ":Sistema": envia uma nota de transferencia com os produtos enviados
activate ":Sistema"
":Sistema" --> FARM: operação bem sucedida
deactivate ":Sistema"
deactivate FARM

@enduml