@startuml
skinparam classAttributeIconSize 0

class AplicacaoPOT
{
  +static getInstance()
  +getSessaoAtual()
}

class Estafeta {
  -String nif
  -String nome
  -String email
  -Double peso
  -Integer nss
  -String pwd
  +Estafeta(nif,nome,email,peso,nss,pwd)
}

class EstafetaDB {
  +getListaEstafetas()
  +getEstafetaByEmail(email)
  +atualizarEstafeta(est)
  +validaEstafeta(est)
}

class AtualizarEstafetaController {
    +getEstafetaByEmail(email)
    +atualizarEstafeta(est)
    +getListaEstafetas()
}

class AtualizarEstafetaUI {
}

AtualizarEstafetaUI ..> AtualizarEstafetaController
AtualizarEstafetaController ..> EstafetaDB
AtualizarEstafetaController ..> Estafeta
AtualizarEstafetaController ..> AplicacaoPOT

EstafetaDB "1" --> "*" Estafeta : tem registados

@enduml
