@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Parque {
  -idParque
  -numeroMaximo
  -tipo
}

class Farmacia {
  -NIF
  -email
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

class Veiculo {
  -idVeiculo
  -descricao
  -percentagemBateria
  -pesoMaximo
  -pesoVeiculo
  -potencia
  -areaFrontal
}

class Drone{
  -idDrone
  -hoverPower
}

Administrador "1" -- "1" Utilizador: atua como >
Administrador "1" -- "1..*" Parque: remove >
Farmacia "1" -- "1" Parque: tem >
Farmacia "1" -- "1" Administrador: tem >
Parque "1" -- "0..*" Veiculo: tem >
Veiculo "1" -- "1" Drone: é <

@enduml