@startuml
autonumber
actor "Administrador" as UNR

activate UNR
UNR -> ":Sistema" : Pretende atualizar um novo drone
activate ":Sistema"
":Sistema" --> UNR : solicita dados do drone(percentagemBateria, pesoMaximo, pesoVeiculo, potencia, areaFrontal, hoverPower)
deactivate ":Sistema"


UNR -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> UNR : apresenta dados e solicita confirmação
deactivate ":Sistema"

UNR -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> UNR : operação bem sucedida
deactivate ":Sistema"

deactivate UNR
@enduml
