@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Produto {
  -idProduto
  -designacao
  -peso
  -precoBase
}

class Farmacia {
  -NIF
  -email
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

Administrador "1" -- "1" Utilizador: atua como >
Administrador "1" -- "*" Produto: atualiza no stock >
Farmacia "1" -- "*" Produto: tem >
Farmacia "1" -- "1" Administrador: tem >

@enduml