@startuml
skinparam classAttributeIconSize 0

class AplicacaoPOT{
  +static getInstance()
  +getSessaoAtual()
}

class SessaoUtilizador{
  +getEmailUtilizador()
}

class ScooterDB {
  +getListaScooter()
}

class EncomendaDB {
  +getListaEncomenda(
}

class Entrega {
  -Integer idEntrega
  -String dataInicio
  -String dataFim
  +create(idEntrega, dataInicio, dataFim)
  +addEstafeta(est)
  +novaEncomenda(idEncomenda, dataPedida, preco, pesoEncomenda, taxa, estadoEncomenda, listaProdutos)
  +addEncomenda(en)
  +novaScooter(idScooter, percentagemBateria, pesoMaximo, pesoScooter, potencia)
  +addScooter(s)
}

class EntregaDB {
  +generateIdEntrega()
  +novaEntrega(idEntrega, dataInicio, dataFim)
  +registaEntrega(entr)
  +validaEntrega(entr)
  +addEntrega(entr)
}

class EstafetaDB {
  +getEstafetaByEmail(email)
}

class RegistarEntregaController {
  +getEstafeta()
  +novaEntrega(dataInicio, dataFim)
  +getListaEncomenda()
  +novaEncomenda(idEncomenda, dataPedida, preco, pesoEncomenda, taxa, estadoEncomenda, listaProdutos)
  +getListaScooter()
  +novaScooter(idScooter, percentagemBateria, pesoMaximo, pesoScooter, potencia)
  +registaEntrega()
}

class RegistarEntregaUI {
}

class Encomenda {
  -Integer idEncomenda
  -String dataPedida
  -Double preco
  -Double pesoEncomenda
  -Double taxa
}

class Estafeta {
  -String NIF
  -String nome
  -String email
  -Integer numeroSegurancaSocial
  -String password
  -Double pesoEstafeta
}

class Scooter {
  -Integer idScooter
  -Double percentagemBateria
  -Double pesoMaximo
  -Double pesoScooter
  -Double potencia
}

class EstadoEncomenda {
  -Integer id_estado_encomenda
  -String designacao
}

class Produto {
  -Integer idProduto
  -String designacao
  -Double peso
  -Double precoBase
}

RegistarEntregaUI ..> RegistarEntregaController

RegistarEntregaController ..> EstafetaDB
RegistarEntregaController ..> EntregaDB
RegistarEntregaController ..> EncomendaDB
RegistarEntregaController ..> ScooterDB
RegistarEntregaController ..> AplicacaoPOT
RegistarEntregaController ..> SessaoUtilizador

EntregaDB "1" --> "*" Entrega : tem registadas
EstafetaDB "1" --> "*" Estafeta : tem registadas
EncomendaDB "1" --> "*" Encomenda : tem registadas
ScooterDB "1" --> "*" Scooter : tem registadas
Encomenda "1" -- "1" EstadoEncomenda : tem >
Entrega "1" -- "*" Encomenda : possui >
Estafeta "1" -- "*" Entrega: realiza >
Entrega "*" -- "1" Scooter: realiza <
Encomenda "1" -- "*" Produto: tem >

@enduml