@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Entrega {
  -idEntrega
  -dataInicio
  -dataFim
}

class Encomenda {
  -idEncomenda
  -dataPedida
  -preco
}

class EstadoEncomenda {
  -id_estado_encomenda
  -designacao
}

class Produto {
  -idProduto
  -designacao
  -peso
  -precoBase
}

class Estafeta {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

class EstadoEstafeta {
  -id_estado_estafeta
  -designacao
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

class Endereco {
  -morada
}

class LocalizacaoGPS {
  -latitude
  -longitude
}

class Parque {
  -numeroMaximo
}

class Scooter {
  -idScooter
  -percentagemBateria
  -pesoMaximo
}

class Cliente {
  -numeroCartaoCredito
  -dataDeValidade
  -CCV
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

Encomenda "1" -- "1" EstadoEncomenda : tem >
Entrega "1" -- "*" Encomenda : possui >
Estafeta "1" -- "*" Entrega: realiza >
Estafeta "1" -- "1" EstadoEstafeta: tem >
Estafeta "1" -- "1" Utilizador: atua como >
Endereco "1" -- "1" LocalizacaoGPS: tem >
Cliente "1" -- "1" Endereco: tem >
Cliente "1" -- "1" Utilizador: atua como >
Cliente "1" -- "*" Encomenda: realiza e paga >
Entrega "*" -- "1" Scooter: realiza <
Encomenda "1" -- "*" Produto: tem >
Parque "1" -- "1" Endereco: tem >
Parque "1" -- "*" Scooter: possui >



@enduml