@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Entrega {
  -idEntrega
  -dataInicio
  -dataFim
}

class Encomenda {
  -idEncomenda
  -dataPedida
  -preco
  -pesoEncomenda
  -taxa
}

class Estafeta {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -pesoEstafeta
}

class Scooter {
  -idScooter
  -percentagemBateria
  -pesoMaximo
  -pesoScooter
  -potencia
  -areaFrontal
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

class EstadoEncomenda {
  -id_estado_encomenda
  -designacao
}

class Produto {
  -idProduto
  -designacao
  -peso
  -precoBase
}

Estafeta "1" -- "1" Utilizador: atua como >
Entrega "1" -- "*" Encomenda : possui >
Estafeta "1" -- "*" Entrega: realiza >
Entrega "*" -- "1" Scooter: realiza <
Encomenda "1" -- "*" Produto: tem >
Encomenda "1" -- "1" EstadoEncomenda : tem >

@enduml