@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Entrega {
  -idEntrega
  -dataInicio
  -dataFim
}

class Encomenda {
  -idEncomenda
  -dataPedida
  -preco
  -pesoEncomenda
}

class Estafeta {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -pesoEstafeta
}

class Scooter {
  -idScooter
  -percentagemBateria
  -pesoMaximo
  -pesoScooter
  -potencia
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

Estafeta "1" -- "1" Utilizador: atua como >
Entrega "1" -- "*" Encomenda : possui >
Estafeta "1" -- "*" Entrega: realiza >
Entrega "*" -- "1" Scooter: realiza <

@enduml