@startuml
skinparam classAttributeIconSize 0

class SessaoUtilizador{
  +getNif()
  +static getInstance()
  +getSessaoAtual()
}

class FarmaciaDB{
  +getLstFarmacias()
}

class VeiculoDB{
  +getListaVeiculoEntrega(pesoMaximoEntrega, nifFarmacia)
}

class EnderecoDB {
  +getEnderecoByNifCliente(nif)
  +getEnderecoOrigem(nifFarmacia)
  +getLstEnderecosScooter()
}

class EncomendaDB {
  +getListaEncomenda(nifFarmacia)
}

class Entrega {
  -Integer idEntrega
  -String dataInicio
  -String dataFim
  -Double pesoEntrega
}

class EntregaDB {
  +generateGraphScooter(listEnderecosScooter, listEnderecos, est, veiculo, pesoEntrega)
  +getPath(graphScooter, listEnderecos, finalShortPathScooter, endereco, 0, veiculo, 0, list)
}

class EstafetaDB {
  +getEstafetaByNIF(nif)
}

class RegistarEntregaController {
  +getEstafeta()
  +getLstFarmacias()
  +getListaEncomenda(nifFarmacia)
  +getEnderecoByNifCliente(nif)
  +getEnderecoOrigem(nifFarmacia)
  +getLstEnderecosScooter()
  +getListaVeiculoEntrega(pesoMaximoEntrega, nifFarmacia)
  +generateGraphScooter(listEnderecosScooter, listEnderecos, est, veiculo, pesoEntrega)
  +getPath(graphScooter, listEnderecos, finalShortPathScooter, endereco, 0, veiculo, 0, list)
}

class RegistarEntregaUI {
}

class Encomenda {
  -Integer idEncomenda
  -String dataPedida
  -Double preco
  -Double pesoEncomenda
  -Double taxa
}

class Estafeta {
  -Double pesoEstafeta
}

class Scooter {
  -Integer idScooter
}

class Endereco {
  -String morada
  -Double latitude
  -Double longitude
  -Double altitude
}

class Cliente {
  -Integer creditos
}

class EstadoEncomenda {
  -Integer idEstadoEncomenda
  -String designacao
}

class Produto {
  -Integer idProduto
  -String designacao
  -Double peso
  -Double precoBase
}

class Utilizador {
  -Integer NIF
  -String nome
  -String email
  -Integer numeroSegurancaSocial
  -String password
}

class Veiculo {
  -Integer idveiculo
  -String descricao
  -Double capacidade
  -Double percentagemBateria
  -Double pesoMaximo
  -Double pesoVeiculo
  -Double potencia
  -Double areaFrontal
}

class Drone {
  -Integer idDrone
  -Double largura
}

class Farmacia {
  -Integer NIF
  -String email
}

RegistarEntregaUI ..> RegistarEntregaController

RegistarEntregaController ..> EstafetaDB
RegistarEntregaController ..> EnderecoDB
RegistarEntregaController ..> FarmaciaDB
RegistarEntregaController ..> EntregaDB
RegistarEntregaController ..> EncomendaDB
RegistarEntregaController ..> VeiculoDB
RegistarEntregaController ..> SessaoUtilizador

EntregaDB "1" --> "*" Entrega : tem registadas
EstafetaDB "1" --> "*" Estafeta : tem registadas
EncomendaDB "1" --> "*" Encomenda : tem registadas
EnderecoDB "1" --> "*" Endereco : tem registadas
FarmaciaDB "1" --> "*" Farmacia : tem registadas
VeiculoDB "1" --> "*" Veiculo : tem registadas

Estafeta "1" -- "1" Utilizador: atua como >
Cliente "1" -- "1" Utilizador: atua como >
Veiculo "1" -- "1" Drone: é <
Veiculo "1" -- "1" Scooter: é <
Entrega "*" -- "1" Veiculo: realiza <
Encomenda "1" -- "*" Produto: tem >
Entrega "1" -- "*" Encomenda : possui >
Estafeta "1" -- "*" Entrega: realiza >
Cliente "1" -- "1" Endereco: tem >
Cliente "1" -- "*" Encomenda: realiza e paga >
Farmacia "1" -- "*" Encomenda: tem >
Farmacia "1" -- "*" Veiculo: possui >
Farmacia "1" -- "1" Endereco: tem >
Encomenda "1" -- "1" EstadoEncomenda : tem >

@enduml