@startuml
autonumber
actor "Estafeta" as EST

participant ":RegistarEntregaUI" as UI
participant ":RegistarEntregaController" as CTRL
participant "AplicacaoPOT" as _APP
participant "app\n:AplicacaoPOT" as APP
participant "sessao\n:SessaoUtilizador" as SESSAO

participant ":EstafetaDB" as ESTDB
participant ":EntregaDB" as ENTRDB

participant ":EncomendaDB" as RENC
participant ":ScooterDB" as RS
participant ":EnderecoDB" as END

activate EST
EST -> UI : inicia entrega
activate UI
UI -> CTRL : getEstafeta()
activate CTRL
CTRL -> _APP: app = getInstance()
activate _APP
|||
deactivate _APP
CTRL -> APP: sessao = getSessaoAtual()
activate APP
|||
deactivate APP

CTRL -> SESSAO: email = getEmailUtilizador()
activate SESSAO
|||
deactivate SESSAO
CTRL -> ESTDB : est=getEstafetaByEmail(email)
activate ESTDB
deactivate ESTDB
deactivate CTRL
UI -> CTRL : getListaEntregaByNifEstafeta(nifEstafeta)
activate CTRL
CTRL -> ENTRDB : listaEntregas=getListaEntregaByNifEstafeta(nifEstafeta)
activate ENTRDB
deactivate ENTRDB
deactivate CTRL
UI --> EST : mostra a lista de entregas do estafeta e solicita escolha de uma entrega
deactivate UI

EST -> UI : introduz dados solicitados
activate UI
UI -> CTRL : getListaEncomendaById(idEntrega)
activate CTRL
CTRL -> RENC : listaEncomendas=getListaEncomendaById(idEntrega)
activate RENC
deactivate RENC
deactivate CTRL
UI -> CTRL : getEntregaById(int idEntrega)
activate CTRL
CTRL -> ENTRDB : entr=getEntregaById(int idEntrega)
activate ENTRDB
deactivate ENTRDB
deactivate CTRL
UI -> CTRL : getScooterById(idScooter)
activate CTRL
CTRL -> RS : scooter=getScooterById(idScooter)
activate RS
deactivate RS
deactivate CTRL


UI --> EST : apresenta dados e solicita confirmação
deactivate UI

EST -> UI : confirma os dados
activate UI
UI -> CTRL : getEnderecoParque()
activate CTRL
CTRL-> END : origem=getEnderecoParque()
activate END
deactivate END
deactivate CTRL
loop
UI -> CTRL : getEnderecoByNifCliente(int nif)
activate CTRL
CTRL -> END : endereco=getEnderecoByNifCliente(nif)
activate END
deactivate END
deactivate CTRL
end loop

UI -> CTRL : generateGraph(listEnderecos, est, scooter, pesoTotal)
activate CTRL
CTRL -> ENTRDB : generateGraph(listEnderecos, est, scooter, pesoTotal)
activate ENTRDB
deactivate ENTRDB
deactivate CTRL
UI --> EST : informa operação bem sucedida
deactivate CTRL
deactivate UI

deactivate EST

@enduml