@startuml
skinparam classAttributeIconSize 0

class VeiculoDB {
  +Scooter setScooter(double percentagem de bateria,double peso máximo)
  +scooterHandler(Scooter scooter)
  +validaScooter(Scooter scooter)
  +addScooter(Scooter scooter)
}

class VeiculoController {
    +Scooter setScooter(double percentagemBateria, double precoMaximo)
    +scooterHandler()
}

class AdminUI {
}

class Veiculo {
   +Scooter setScooter(percentagem de bateria,peso máximo)
}

AdminUI ..> VeiculoController 

VeiculoController ..> VeiculoDB
VeiculoDB ..> Veiculo
@enduml
