@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Estafeta {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
  -pesoEstafeta
}

class Entrega {
  -idEntrega
  -dataInicio
  -dataFim
}

class Veiculo {
  -idVeiculo
  -descricao
  -tipo
  -percentagemBateria
  -pesoMaximo
  -pesoVeiculo
  -potencia
  -areaFrontal
}

class Parque {
  -idParque
  -numeroMaximo
  -tipo
}

class Farmacia {
  -NIF
  -email
  -morada
}

class Utilizador {
  -NIF
  -nome
  -email
  -numeroSegurancaSocial
  -password
}

Estafeta "1" -- "*" Entrega: realiza >
Entrega "*" -- "1" Veiculo: realiza <
Parque "1" -- "*" Veiculo: possui >
Farmacia "1" -- "1" Parque: possui >
Farmacia "1" -- "*" Estafeta: tem >
Farmacia "1" -- "1" Administrador: tem >
Administrador "1" -- "1" Utilizador: atua como >
Administrador "1" -- "1..*" Estafeta: notifica

@enduml
