@startuml
skinparam classAttributeIconSize 0

class EmailDB {
  +sendEmail(emailFarmacia, emailCliente, assunto, mensagem)
  +validaNota(farmacia, cliente)
  +enviarNotaCliente(farmacia, cliente)
}

class RegistarEntregaController {
    +enviarNotaCliente(farmacia, cliente)
}

class RegistarEntregaUI {
}



RegistarEntregaUI ..> RegistarEntregaController
RegistarEntregaController ..> EmailDB


@enduml
