@startuml
autonumber

actor "Estafeta" as EST
participant ":RegistarEntregaUI" as UI
participant ":RegistarEntregaController" as CTL
participant ":EmailDB" as PDB

activate EST
EST -> UI : envia uma nota a um cliente quando a sua entrega começar
activate UI
UI -> CTL : enviarNotaCliente(farmacia, cliente)
activate CTL


CTL -> PDB : sendEmail(emailFarmacia, emailCliente, assunto, mensagem)
activate PDB

PDB -> PDB : validaNota(farmacia, cliente)

PDB -> PDB : enviarNotaCliente(farmacia, cliente)

deactivate PDB

deactivate CTL

UI --> EST : operação bem sucedida
deactivate UI

deactivate EST
@enduml
